limit yapfify-ing to region if active
JorisE/yapfify.el pull request #5
Opened 2017-04-20 20:21 UTC by toshism

As was mentioned in issue #3, If you have an active region the formatting is limited to those *lines*. If there is no active region the behavior is unchanged.

I'm not sure that `yapfify-buffer` still works for the name, but I'll leave that to someone else to decide.

Note: This is entirely line based. If your region start point is at the very end of line 4, all of line 4 is formatted. Same for the end point.

2017-04-21 13:55 UTC, toshism commented
After using this for a bit yesterday I found it a bit awkward having the buffer jump around after running yapfify with a selection. I added an additional commit to improve this. The buffer is restored (as close as possible considering the code could have changed) to the original state.

2017-04-23 19:11 UTC, JorisE requested changes

2017-04-23 19:11 UTC, JorisE commented on yapfify.el
> +         (end-line (line-number-at-pos (get-end-point)))
This returns one linenumber higher than expected. I.e. Select a region ending at line 2 and this will return 3.

2017-04-23 19:12 UTC, JorisE commented
Looking good! Thanks a lot.

I found one unexpected thing that is addressed in the review.

2017-04-25 14:55 UTC, toshism commented
Ah thanks, good catch. I'm guessing it's when point/mark is at the end of the line most likely (I don't write much elisp)...

Regardless, I'll fix that up this week when I get a minute.

2017-04-28 13:46 UTC, toshism commented
It's not pretty, but it works as expected now.

2017-05-05 05:17 UTC, merged

2017-05-05 05:20 UTC, JorisE commented
Thanks! That does look strange :) But it looks like it works correctly